.TH clematis-console 1 "2024-01-01" "Clematis 0.10.0" "User Commands"
.SH NAME
clematis\-console \\\- Delegates to scripts/ for 'console'
.SH SYNOPSIS
usage: clematis console console [\-h]
.SH DESCRIPTION
Delegates to scripts/ for 'console'
.SH OPTIONS
.nf
usage: clematis console console [\-h]

options:
  \-h, \-\-help  show this help message and exit
.fi
