.TH clematis-chat 1 "2024-01-01" "Clematis 0.10.2" "User Commands"
.SH NAME
clematis\-chat \\\- Delegates to scripts/ for 'chat'
.SH SYNOPSIS
usage: clematis chat chat [\-h]
.SH DESCRIPTION
Delegates to scripts/ for 'chat'
.SH OPTIONS
.nf
usage: clematis chat chat [\-h]

options:
  \-h, \-\-help  show this help message and exit
.fi
