.TH clematis-inspect-snapshot 1 "2024-01-01" "Clematis 0.8.0a0" "User Commands"
.SH NAME
clematis\-inspect\-snapshot \\\- Delegates to scripts/ for 'inspect\-snapshot'
.SH SYNOPSIS
usage: clematis inspect\-snapshot [\-h] ...
.SH DESCRIPTION
Delegates to scripts/ for 'inspect\-snapshot'
.SH OPTIONS
.nf
usage: clematis inspect\-snapshot [\-h] ...

Delegates to scripts/inspect_snapshot.py

positional arguments:
  args        Pass\-through arguments for scripts/inspect_snapshot.py.

options:
  \-h, \-\-help  show this help message and exit
.fi
