.TH clematis-validate 1 "2024-01-01" "Clematis 0.10.2" "User Commands"
.SH NAME
clematis\-validate \\\- Delegates to scripts/ for 'validate'
.SH SYNOPSIS
usage: clematis validate validate [\-\-json | \-\-table] [\-\-quiet] [\-\-verbose] [\-h]
.SH DESCRIPTION
Delegates to scripts/ for 'validate'
.SH OPTIONS
.nf
usage: clematis validate validate [\-\-json | \-\-table] [\-\-quiet] [\-\-verbose] [\-h]

Delegates to scripts<PATH>

options:
  \-\-json      JSON output (stable, machine\-readable)
  \-\-table     Plain table output (no color)
  \-\-quiet     suppress non\-essential stderr
  \-\-verbose   increase stderr verbosity
  \-h, \-\-help  show this help message and exit
.fi
