.TH clematis-bench-t4 1 "2024-01-01" "Clematis 0.8.0a0" "User Commands"
.SH NAME
clematis\-bench\-t4 \\\- Delegates to scripts/ for 'bench\-t4'
.SH SYNOPSIS
usage: clematis bench\-t4 [\-h] ...
.SH DESCRIPTION
Delegates to scripts/ for 'bench\-t4'
.SH OPTIONS
.nf
usage: clematis bench\-t4 [\-h] ...

Delegates to scripts/bench_t4.py

positional arguments:
  args        Pass\-through arguments for scripts/bench_t4.py.

options:
  \-h, \-\-help  show this help message and exit
.fi
