[package]
name = "clematis_native_t1"
version = "0.1.0"
edition = "2021"

[lib]
name = "_t1_rs"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
numpy = "0.21"
ordered-float = "3"
