k_surface: 32
surface_method: PCA
t1:
  decay:
    mode: exp_floor
    rate: 0.6
    floor: 0.05
  edge_type_mult: {supports: 1.0, associates: 0.6, contradicts: 0.8}
  iter_cap: 50
  node_budget: 1.5
  queue_budget: 10000
  radius_cap: 4
  cache:
    enabled: true
    max_entries: 512
    ttl_s: 300
t2:
  backend: inmemory
  k_retrieval: 64
  sim_threshold: 0.3
  tiers: [exact_semantic, cluster_semantic, archive]
  exact_recent_days: 30
  ranking: {alpha_sim: 0.75, beta_recency: 0.2, gamma_importance: 0.05}
  clusters_top_m: 3
  owner_scope: any
  residual_cap_per_turn: 32
  cache:
    enabled: true
    max_entries: 512
    ttl_s: 300
  lancedb:
    uri: ./.data/lancedb
    table: episodes
    meta_table: meta
    index:
      metric: cosine
      ef_search: 64
      m: 16
t3:
  max_rag_loops: 1
  tokens: 256
  temp: 0.7
  max_ops_per_turn: 3
  allow_reflection: false
  backend: rulebased
  dialogue:
    template: "{style_prefix}| summary: {labels}. next: {intent}"
    include_top_k_snippets: 2
  policy:
    tau_high: 0.8
    tau_low: 0.4
    epsilon_edit: 0.10
  llm:
    provider: qwen
    model: qwen3-4b-instruct
    temperature: 0.2
    max_tokens_default: 256
    timeout_s: 30
t4:
  enabled: true
  delta_norm_cap_l2: 1.5
  novelty_cap_per_node: 0.3
  churn_cap_edges: 64
  cooldowns:
    EditGraph: 2
    CreateGraph: 10
  weight_min: -1.0
  weight_max: 1.0
  snapshot_every_n_turns: 1
  snapshot_dir: ./.data/snapshots
  cache_bust_mode: on-apply
  cache:
    enabled: true
    namespaces:
      - "t2:semantic"
    max_entries: 512
    ttl_sec: 600
budgets: {time_ms: 1000, ops: 1000, tokens: 1024, time_ms_reflection: 6000}
flags: {enable_world_memory: true, allow_reflection: true}
# -----------------------------------------------------------------------------
# Scheduler (M5) — Example config (feature-flagged; defaults live in validate.py)
# -----------------------------------------------------------------------------
# scheduler:
#   enabled: false
#   policy: round_robin   # or fair_queue
#   quantum_ms: 20
#   budgets:
#     t1_pops: null       # int or null
#     t1_iters: 50
#     t2_k: 64            # cap on results USED (not fetched)
#     t3_ops: 3
#     wall_ms: 200        # must be >= quantum_ms
#   fairness:
#     max_consecutive_turns: 1  # enforced in PR27
#     aging_ms: 200              # bucket size for fair-queue priority