name: ci
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # If you added requirements-dev.txt, this will install dev deps
      - name: Install dev deps (if present)
        run: |
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          else
            pip install pytest numpy
          fi

      # Install your package in editable mode (so `from clematis...` works)
      - name: Install package
        run: pip install -e .

      - name: Run tests
        run: pytest -q