name: ci
on:
  push: { branches: [main] }
  pull_request: { branches: [main] }

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      # If you added requirements-dev.txt, this will install dev deps
      - name: Install dev deps (if present)
        run: |
          if [ -f requirements-dev.txt ]; then
            pip install -r requirements-dev.txt
          else
            pip install pytest
          fi
          # Ensure minimal test deps are present regardless
          pip install pyyaml

      # Install your package in editable mode (so `from clematis...` works)
      - name: Install package
        run: pip install -e .

      - name: Sanity imports
        run: |
          python - <<'PY'
          import sys, traceback
          print("python:", sys.version)
          try:
              import yaml
              print("yaml:", getattr(yaml, "__version__", "unknown"))
          except Exception as e:
              print("YAML import failure:", e); traceback.print_exc(); raise
          try:
              import clematis
              print("clematis package import: OK")
              import clematis.engine.stages.t4 as t4
              print("t4 import: OK; has t4_filter?", hasattr(t4, "t4_filter"))
          except Exception as e:
              print("Clematis import failure:", e); traceback.print_exc(); raise
          PY

      - name: Run tests
        run: pytest -q