name: CLI Smokes

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install
        run: |
          python -m pip install -U pip
          pip install -e .[dev]
      - name: CLI help smokes (PR46)
        env:
          CI: "true"
          CLEMATIS_NETWORK_BAN: "1"
        run: |
          python -m clematis --help
          python -m clematis rotate-logs --help
          python -m clematis inspect-snapshot --help
          python -m clematis bench-t4 --help
          python -m clematis seed-lance-demo --help
