name: disabled-path-identity

on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: identity-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  identity:
    name: Golden identity (scheduler.disabled)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      LC_ALL: C
      PYTHONUTF8: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml', '**/setup.cfg', '**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        shell: bash
        run: |
          set -euxo pipefail
          export PIP_DISABLE_PIP_VERSION_CHECK=1
          python3 -m pip install --upgrade pip
          # Prefer project editable install
          if [ -f pyproject.toml ] || [ -f setup.cfg ] || [ -f setup.py ]; then
            python3 -m pip install -e ".[dev,test]" || python3 -m pip install -e .
          fi
          # Project requirements
          if [ -f requirements-dev.txt ]; then
            python3 -m pip install -r requirements-dev.txt
          elif [ -f requirements.txt ]; then
            python3 -m pip install -r requirements.txt
          else
            python3 -m pip install pytest pyyaml numpy
          fi
          # Optional runtime used by snapshots; harmless if unused
          python3 -m pip install --quiet zstandard || true

      - name: Validate repo config (non-strict if present)
        shell: bash
        run: |
          set -euxo pipefail
          if [ -f scripts/validate_config.py ] && [ -f configs/config.yaml ]; then
            python3 scripts/validate_config.py configs/config.yaml || true
          fi

      - name: Validate strict (quiet) config
        shell: bash
        run: |
          set -euxo pipefail
          if [ -f scripts/validate_config.py ]; then
            python3 scripts/validate_config.py .ci/validator_strict_quiet.yaml --strict
          else
            echo "scripts/validate_config.py not found"; exit 1
          fi

      - name: Identity unit test
        env:
          CLEMATIS_NETWORK_BAN: "1"
          CI: "true"
          CLEMATIS_LOG_DIR: /tmp/logs
        shell: bash
        run: |
          set -euxo pipefail
          pytest -q -m "not manual" tests/test_identity_disabled_path.py::test_disabled_perf_and_quality_identity_to_base

      - name: CLI validator smoke (quiet config)
        env:
          CLEMATIS_NETWORK_BAN: "1"
          CI: "true"
          CLEMATIS_LOG_DIR: /tmp/logs
        shell: bash
        run: |
          set -euxo pipefail
          pytest -q -m "not manual" tests/test_config_perf_quality.py::test_cli_validator_smoke

      - name: Run golden disabled identity guard
        env:
          CLEMATIS_NETWORK_BAN: "1"
          CI: "true"
          IDENTITY_TESTS: "1"
        shell: bash
        run: |
          set -euo pipefail
          # Ensure identity uses the default .logs and starts clean
          unset CLEMATIS_LOG_DIR || true
          rm -rf .logs
          mkdir -p .logs
          # Use the shared Python guard which generates logs, normalizes, and compares
          python3 scripts/ci_compare_golden.py

      - name: Upload artifacts on failure
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: identity-diagnostics
          path: |
            ./.logs/**
            ./.norm/**
            ./.gold_norm/**
          if-no-files-found: ignore
