name: identity-parallel

on:
  push:
    branches: ["**"]
    paths:
      - 'clematis/**'
      - 'tests/**'
      - 'docs/m9/**'
      - '.github/workflows/identity_parallel.yml'
  pull_request:
    paths:
      - 'clematis/**'
      - 'tests/**'
      - 'docs/m9/**'
      - '.github/workflows/identity_parallel.yml'

env:
  TZ: UTC
  PYTHONUTF8: "1"
  PYTHONHASHSEED: "0"
  LC_ALL: C.UTF-8
  SOURCE_DATE_EPOCH: "315532800"

jobs:
  identity-parallel:
    name: Identity (seq vs par) [${{ matrix.os }} | py${{ matrix.python-version }} | ${{ matrix.mode }}]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11', '3.12', '3.13']
        mode: ['off', 'on']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          check-latest: true

      - name: Install
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[test]"

      - name: Set deterministic env
        run: |
          echo "SOURCE_DATE_EPOCH=315532800" >> $GITHUB_ENV
          echo "CLEMATIS_NETWORK_BAN=1" >> $GITHUB_ENV
          echo "PYTHONHASHSEED=0" >> $GITHUB_ENV
          echo "PYTHONUTF8=1" >> $GITHUB_ENV
          echo "PYTHONIOENCODING=UTF-8" >> $GITHUB_ENV
          echo "TZ=UTC" >> $GITHUB_ENV
          echo "LC_ALL=C.UTF-8" >> $GITHUB_ENV
          echo "PIP_DISABLE_PIP_VERSION_CHECK=1" >> $GITHUB_ENV

      - name: Disable Git autocrlf on Windows
        if: runner.os == 'Windows'
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Run identity tests
        env:
          ID_MODE: ${{ matrix.mode }}
        run: |
          set -euo pipefail
          if [ "$ID_MODE" = "off" ]; then
            pytest -q tests/integration/test_identity_parallel.py
          else
            pytest -q tests/integration/test_identity_parallel.py
            pytest -q tests/integration/test_race_regression.py
          fi

      - name: Atomic IO tests (Windows only)
        if: runner.os == 'Windows'
        run: |
          pytest -q tests/io/test_atomic_writes.py
          pytest -q tests/snapshots/test_snapshot_writer_roundtrip.py
