name: Lint & Types
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      COLUMNS: 80
      TZ: UTC
      PYTHONHASHSEED: 0
      PYTHONUTF8: 1
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          check-latest: true
          cache: "pip"
          cache-dependency-path: |
            requirements-dev.txt

      - name: Install pinned dev toolchain
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install -e .

      - name: "Pre-commit (pinned hooks: ruff + mypy)"
        run: pre-commit run --all-files --show-diff-on-failure
