name: Lint & Types
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]
      - name: Ruff (format check)
        run: ruff format --check .
      - name: Ruff (lint)
        run: ruff check --force-exclude .
      - name: Mypy (CLI only)
        run: mypy --config-file pyproject.toml
