name: Lint & Types
on:
  pull_request:
  push:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dev tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[dev]
      - name: Ruff (lint — safety set repo-wide)
        run: ruff check --force-exclude --select E9,F63,F7,F82 .
      - name: Ruff (lint — CLI strict)
        run: ruff check --force-exclude clematis/cli
      - name: Mypy (CLI only)
        run: mypy --config-file pyproject.toml
