name: Reproducible Build (sdist & wheel)

on:
  pull_request:
    paths:
      - "pyproject.toml"
      - "MANIFEST.in"
      - "clematis/**"
      - "docs/m8/**"
      - ".github/workflows/**"
  push:
    branches: [ main ]

jobs:
  reproducible:
    runs-on: ubuntu-latest
    env:
      # Repro knobs
      SOURCE_DATE_EPOCH: "1704067200"   # 2024-01-01T00:00:00Z (example)
      PYTHONHASHSEED: "0"
      TZ: "UTC"
      LC_ALL: "C.UTF-8"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      CLEMATIS_NETWORK_BAN: "1"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip build

      - name: Build #1
        run: |
          set -euo pipefail
          rm -rf build dist *.egg-info
          python -m build
          ls -l dist

      - name: Canonicalize & hash #1
        run: |
          set -euo pipefail
          SDIST=$(ls dist/*.tar.gz)
          WHEEL=$(ls dist/*.whl)
          TMP=$(mktemp -d)
          # Ungzip to tar, normalize tar metadata and order, then gzip with fixed header
          gzip -dc "$SDIST" | tar -C "$TMP" -x
          tar --mtime="@$SOURCE_DATE_EPOCH" \
              --sort=name --owner=0 --group=0 --numeric-owner \
              -cf /tmp/sdist1.tar -C "$TMP" .
          gzip -n -c /tmp/sdist1.tar > /tmp/sdist1.tgz
          sha256sum "$WHEEL" /tmp/sdist1.tgz > /tmp/hashes1.txt

      - name: Build #2 (clean)
        run: |
          set -euo pipefail
          rm -rf build dist *.egg-info
          python -m build
          ls -l dist

      - name: Canonicalize & hash #2 and compare
        run: |
          set -euo pipefail
          SDIST=$(ls dist/*.tar.gz)
          WHEEL=$(ls dist/*.whl)
          TMP=$(mktemp -d)
          gzip -dc "$SDIST" | tar -C "$TMP" -x
          tar --mtime="@$SOURCE_DATE_EPOCH" \
              --sort=name --owner=0 --group=0 --numeric-owner \
              -cf /tmp/sdist2.tar -C "$TMP" .
          gzip -n -c /tmp/sdist2.tar > /tmp/sdist2.tgz
          sha256sum "$WHEEL" /tmp/sdist2.tgz > /tmp/hashes2.txt
          echo "=== DIFF (should be empty) ==="
          diff -u /tmp/hashes1.txt /tmp/hashes2.txt