name: PR37 — Lexical Fusion Smoke

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CLEMATIS_GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  fusion-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Export GIT SHA
        run: |
          echo "CLEMATIS_GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -e ".[dev]"

      - name: Run tests w/ PR37 enabled (fusion)
        env:
          CLEMATIS_CONFIG: examples/quality/lexical_fusion.yaml
          CLEMATIS_NETWORK_BAN: "1"
          CI: "true"
        run: |
          . .venv/bin/activate
          pytest -q --maxfail=1 -m "not manual"

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pr37-smoke-logs
          path: |
            logs/quality/**
            .pytest_cache/**
          if-no-files-found: ignore