name: PR37 — Lexical Fusion Smoke

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  CLEMATIS_GIT_SHA: ${{ github.event.pull_request.head.sha || github.sha }}

jobs:
  fusion-smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install deps
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install -e ".[dev]"

      - name: Run tests w/ PR37 enabled (fusion)
        env:
          CLEMATIS_CONFIG: examples/quality/lexical_fusion.yaml
        run: |
          . .venv/bin/activate
          pytest -q --maxfail=1