

name: PR40 Reader Parity Smoke

on:
  pull_request:
    paths:
      - 'clematis/**'
      - 'configs/**'
      - 'tests/**'
      - '.github/workflows/pr40_reader_parity_smoke.yml'
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [flat, auto, partition]
    env:
      CLEMATIS_GIT_SHA: ${{ github.sha }}
      T2_READER_MODE: ${{ matrix.mode }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install -U pip wheel
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            python -m pip install pytest hypothesis
          fi
          if [ -f pyproject.toml ] || [ -f setup.py ]; then
            python -m pip install -e .
          fi

      - name: Run reader parity smoke tests
        shell: bash
        run: |
          pytest -q tests/integration/test_t2_reader_parity.py -q

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pr40-smoke-${{ matrix.mode }}
          path: |
            .pytest_cache
            **/logs/quality/**
          if-no-files-found: ignore