name: PR40 Reader Parity Smoke

on:
  pull_request:
    paths:
      - 'clematis/**'
      - 'configs/**'
      - 'tests/**'
      - '.github/workflows/pr40_reader_parity_smoke.yml'
  workflow_dispatch:

jobs:
  smoke:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        mode: [flat, auto, partition]
    env:
      T2_READER_MODE: ${{ matrix.mode }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Export GIT SHA
        run: |
          echo "CLEMATIS_GIT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install -U pip wheel
          if [ -f requirements.txt ]; then
            python -m pip install -r requirements.txt
          else
            python -m pip install pytest hypothesis
          fi
          if [ -f pyproject.toml ] || [ -f setup.py ]; then
            python -m pip install -e .
          fi

      - name: Run reader parity smoke tests
        env:
          CLEMATIS_NETWORK_BAN: "1"
          CI: "true"
        shell: bash
        run: |
          pytest -q -m "not manual" tests/integration/test_t2_reader_parity.py

      - name: Upload artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: pr40-smoke-${{ matrix.mode }}
          path: |
            logs/quality/**
            .pytest_cache/**
          if-no-files-found: ignore
