

name: strict-parity-nightly

on:
  schedule:
    - cron: "0 20 * * *"   # daily at 20:00 UTC
  workflow_dispatch: {}

concurrency:
  group: strict-parity-nightly-${{ github.ref }}
  cancel-in-progress: true

jobs:
  strict-parity:
    runs-on: ubuntu-22.04
    env:
      CLEMATIS_LOG_DIR: /tmp/logs
    timeout-minutes: 25
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'

      - uses: dtolnay/rust-toolchain@stable

      - name: Install deps
        run: |
          python -m pip install --upgrade pip wheel setuptools
          python -m pip install pytest pytest-timeout pyyaml

      - name: Build & install wheel
        run: |
          python -m pip wheel . -w wheelhouse --no-deps
          python -m pip install --find-links=wheelhouse clematis

      - name: Sanity check native import (no shadowing)
        working-directory: /tmp
        env:
          PYTHONNOUSERSITE: "1"
        run: |
          python - <<'PY'
          import importlib.util
          spec = importlib.util.find_spec('clematis.native._t1_rs')
          print('ext spec:', spec)
          import clematis.native.t1 as n
          print('available():', n.available())
          assert n.available(), 'native module should be available from installed wheel'
          PY

      - name: Run strict-parity suites
        working-directory: /tmp
        env:
          CI: "true"
          CLEMATIS_NETWORK_BAN: "1"
          PERF_SMOKE: "1"
          CLEMATIS_NATIVE_T1: "1"
          CLEMATIS_STRICT_PARITY: "1"
        run: |
          set -e
          # perf smoke (Linux-only test file)
          pytest --maxfail=1 -q $GITHUB_WORKSPACE/tests/perf/test_bench_t1_smoke.py -m slow
          # diagnostics & parity-focused tests
          pytest --maxfail=1 -q $GITHUB_WORKSPACE/tests/native

      - name: Upload native diagnostics (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: t1-native-diagnostics
          path: /tmp/logs/t1_native_diag.jsonl
          if-no-files-found: ignore
          retention-days: 7
